use vcard::{
    Address, Email, FormattedName, Gender, Name, Nickname, Note, Photo, Pref, Rev, Tel, TimeZone,
    TypeValue, Uid, Url, VCard,
    values::{AddressValue, Date, GenderValue, NameValue, Sex, TelValue, TextOrUri, TzValue, Uri},
};

fn main() {
    let mut vcard = VCard::new("David Wang");

    let mut chinese_name = FormattedName::from("王大衛");
    chinese_name.parameters.language = Some("zh-Hant".parse().unwrap());
    vcard.formatted_names.push(chinese_name);

    vcard.names.push(Name::new(NameValue {
        family_names: vec![String::from("Wang")],
        given_names: vec![String::from("David")],
        ..NameValue::default()
    }));

    vcard.nicknames.push(Nickname::new(vec![String::from("Dave"), String::from("大衛")]));

    // Embed the photo file as a base64 data URI.
    vcard.photos.push(Photo::new(Uri::from_file("examples/data/photo.png").unwrap()));

    vcard.birthday =
        Some(vcard::Birthday::new(Date::from_year_month_day(1990, 1, 2).unwrap().into()));

    vcard.gender = Some(Gender::new(GenderValue {
        sex: Some(Sex::Male), identity: None
    }));

    let mut home_address = Address::new(AddressValue {
        street_addresses: vec![String::from("No.5 Xinyi Road")],
        localities: vec![String::from("Taipei")],
        postal_codes: vec![String::from("110")],
        countries: vec![String::from("Taiwan")],
        ..AddressValue::default()
    });
    home_address.parameters.types.push(TypeValue::Home);
    vcard.addresses.push(home_address);

    let mut cell_phone = Tel::new(TelValue::Uri("tel:+886-912-345-678".parse().unwrap()));
    cell_phone.parameters.pref = Some(Pref::new(1).unwrap());
    cell_phone.parameters.types.extend([TypeValue::Cell, TypeValue::Text]);
    vcard.telephones.push(cell_phone);

    let mut work_email = Email::new("david.wang@example.com".parse().unwrap());
    work_email.parameters.types.push(TypeValue::Work);
    vcard.emails.push(work_email);

    vcard.time_zones.push(TimeZone::new(TzValue::from_time_zone(chrono_tz::Tz::Asia__Taipei)));

    vcard.notes.push(Note::from("This card is generated by the vcard crate."));

    vcard.revision = Some(Rev::new(vcard::values::Timestamp::now()));

    vcard.uid =
        Some(Uid::new(TextOrUri::from_uuid_str("550e8400-e29b-41d4-a716-446655440000").unwrap()));

    vcard.urls.push(Url::new("https://magiclen.org".parse().unwrap()));

    print!("{vcard}");
}
