use std::fmt::{self, Formatter};

mod address;
mod anniversary;
mod begin;
mod birthday;
mod calendar_address_uri;
mod calendar_uri;
mod category;
mod client_property_id_map;
mod email;
mod end;
mod fburl;
mod formatted_name;
mod gender;
mod geo;
mod impp;
mod key;
mod language;
mod logo;
mod member;
mod name;
mod nickname;
mod note;
mod organization;
mod photo;
mod product_id;
mod relationship;
mod revision;
mod role;
mod sound;
mod source;
mod telephone;
mod time_zone;
mod title;
mod uid;
mod url;
mod version;
mod x_property;

pub use self::address::Address;
pub use self::anniversary::Anniversary;
pub use self::begin::Begin;
pub use self::birthday::Birthday;
pub use self::calendar_address_uri::CalendarAddressURI;
pub use self::calendar_uri::CalendarURI;
pub use self::category::Category;
pub use self::client_property_id_map::ClientPropertyIDMap;
pub use self::email::Email;
pub use self::end::End;
pub use self::fburl::FBURL;
pub use self::formatted_name::FormattedName;
pub use self::gender::Gender;
pub use self::geo::Geo;
pub use self::impp::IMPP;
pub use self::key::Key;
pub use self::language::Language;
pub use self::logo::Logo;
pub use self::member::Member;
pub use self::name::Name;
pub use self::nickname::NickName;
pub use self::note::Note;
pub use self::organization::Organization;
pub use self::photo::Photo;
pub use self::product_id::ProductID;
pub use self::relationship::Relationship;
pub use self::revision::Revision;
pub use self::role::Role;
pub use self::sound::Sound;
pub use self::source::Source;
pub use self::telephone::Telephone;
pub use self::time_zone::TimeZone;
pub use self::title::Title;
pub use self::uid::UID;
pub use self::url::URL;
pub use self::version::Version;
pub use self::x_property::XProperty;

pub trait Property {
    fn fmt(&self, f: &mut Formatter) -> Result<(), fmt::Error>;
}
